# Set the language
language: node_js

# Set the Node version
node_js:
  - '14'

services:
  # Use Docker command line
  - docker

install:
  # Install dependencies for tests
  - echo -e "Host $INSTANCE\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo snap install doctl
  - npm ci

script:
  # Run tests
  - npm run test

deploy:
  # Build Docker container and push to Docker Hub
  provider: script
  script: bash deploy.sh
  on:
    branch: master
