# Pull from a base image
FROM node:14-alpine

# Use app/ as the working directory
WORKDIR /app

# Copy the files from the current directory to app/
COPY . /app/

# Install dependencies (npm ci is similar to npm i, but for automated builds)
RUN npm ci

# Build production application
RUN npm run build

# Listen on the specified port
EXPOSE 3000

# Run application
CMD ["npm", "run", "start:prod"]
